baseURL = 'http://issadarkthing.com/'
languageCode = 'en-us'
title = "issadarkthing's journal"
theme = "etch"

[params]
  description = "issadarkthing rambling's"
  copyright = "Copyright © 2021 Raziman"
  dark = "on"
  highlight = true

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "posts"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "about"
  url = "/about/"
  weight = 20
