baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "issadarkthing's journal"

[params]
  description = "issadarkthing rambling's"
  copyright = "Copyright © 2021 Raziman"
  highlight = true

