baseURL = 'http://issadarkthing.com/'
languageCode = 'en-us'
title = "issadarkthing's journal"
theme = "etch"

[params]
  description = "issadarkthing rambling's"
  copyright = "Copyright © 2021 Raziman"
  dark = "on"
  highlight = true

