baseURL = 'http://issadarkthing.com/'
languageCode = 'en-us'
title = "journal of issadarkthing"
theme = "etch"
pygmentsUseClasses = true
pygmentsCodeFences = true
googleAnalytics = "G-17S8480P0Z"
enableRobotsTXT = true
disqusShortname = "issadarkthing-com"

[params]
  description = "blog that discusses about open source software"
  copyright = "Copyright © 2021 issadarkthing"
  dark = "on"
  highlight = true

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "posts"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "about"
  url = "/about/"
  weight = 20

[permalinks]
  posts = "/:title/"
